# Generated by Django 5.2.14 on 2026-06-06 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kino", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KinoWindowAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("window_size", models.IntegerField()),
                ("step_size", models.IntegerField()),
                ("start_time", models.BigIntegerField()),
                ("end_time", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "end_draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="window_ends",
                        to="kino.kinodraw",
                    ),
                ),
                (
                    "start_draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="window_starts",
                        to="kino.kinodraw",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
                "unique_together": {
                    ("window_size", "step_size", "start_draw", "end_draw")
                },
            },
        ),
        migrations.CreateModel(
            name="KinoWindowNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("count", models.IntegerField()),
                ("percentage", models.FloatField()),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="numbers",
                        to="kino.kinowindowanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("analysis", "number")},
            },
        ),
    ]
