# Generated by Django 5.2.14 on 2026-06-06 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kino", "0002_kinowindowanalysis_kinowindownumber"),
    ]

    operations = [
        migrations.CreateModel(
            name="KinoWindowAnchor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("anchor_type", models.CharField(max_length=20)),
                ("heat", models.IntegerField()),
                ("anchor_appearances", models.IntegerField(default=0)),
                ("first_half_anchor_appearances", models.IntegerField(default=0)),
                ("second_half_anchor_appearances", models.IntegerField(default=0)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anchors",
                        to="kino.kinowindowanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["anchor_type", "-heat", "number"],
                "unique_together": {("analysis", "number")},
            },
        ),
        migrations.CreateModel(
            name="KinoWindowRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("related_number", models.IntegerField()),
                ("total_count", models.IntegerField(default=0)),
                ("first_half_count", models.IntegerField(default=0)),
                ("second_half_count", models.IntegerField(default=0)),
                ("change", models.IntegerField(default=0)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations",
                        to="kino.kinowindowanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["-total_count", "related_number"],
                "unique_together": {("anchor", "related_number")},
            },
        ),
    ]
