# Generated by Django 5.2.14 on 2026-06-08 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kino", "0003_kinowindowanchor_kinowindowrelation"),
    ]

    operations = [
        migrations.CreateModel(
            name="KinoShapeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shape", models.CharField(max_length=40)),
                ("center_number", models.IntegerField()),
                ("center_row", models.IntegerField()),
                ("center_col", models.IntegerField()),
                ("shape_numbers", models.JSONField()),
                ("hit_numbers", models.JSONField()),
                ("hit_count", models.IntegerField()),
                ("shape_size", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shape_events",
                        to="kino.kinodraw",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KinoShapeMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shape", models.CharField(max_length=40)),
                ("from_draw_id", models.BigIntegerField()),
                ("to_draw_id", models.BigIntegerField()),
                ("from_center", models.IntegerField()),
                ("to_center", models.IntegerField()),
                ("delta_row", models.IntegerField()),
                ("delta_col", models.IntegerField()),
                ("gap", models.IntegerField()),
                ("overlap_score", models.IntegerField(default=0)),
                ("distance_score", models.IntegerField(default=0)),
                ("mode", models.CharField(default="one-to-one", max_length=30)),
                ("future_window", models.IntegerField(default=10)),
                ("min_hits", models.IntegerField(default=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements_from",
                        to="kino.kinoshapeevent",
                    ),
                ),
                (
                    "to_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements_to",
                        to="kino.kinoshapeevent",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="kinoshapeevent",
            index=models.Index(fields=["shape"], name="kino_kinosh_shape_47df07_idx"),
        ),
        migrations.AddIndex(
            model_name="kinoshapeevent",
            index=models.Index(
                fields=["center_number"], name="kino_kinosh_center__023567_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kinoshapeevent",
            index=models.Index(fields=["draw"], name="kino_kinosh_draw_id_d49347_idx"),
        ),
        migrations.AddIndex(
            model_name="kinoshapeevent",
            index=models.Index(
                fields=["shape", "center_number"], name="kino_kinosh_shape_dff6da_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="kinoshapeevent",
            unique_together={("draw", "shape", "center_number", "hit_count")},
        ),
        migrations.AddIndex(
            model_name="kinoshapemovement",
            index=models.Index(fields=["shape"], name="kino_kinosh_shape_3fbd16_idx"),
        ),
        migrations.AddIndex(
            model_name="kinoshapemovement",
            index=models.Index(
                fields=["delta_row", "delta_col"], name="kino_kinosh_delta_r_528c2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kinoshapemovement",
            index=models.Index(fields=["gap"], name="kino_kinosh_gap_81af91_idx"),
        ),
        migrations.AddIndex(
            model_name="kinoshapemovement",
            index=models.Index(
                fields=["from_center", "to_center"],
                name="kino_kinosh_from_ce_340ab1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kinoshapemovement",
            index=models.Index(fields=["mode"], name="kino_kinosh_mode_1ef494_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="kinoshapemovement",
            unique_together={
                ("from_event", "to_event", "mode", "future_window", "min_hits")
            },
        ),
    ]
