# Generated by Django 5.2.14 on 2026-06-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kino", "0004_kinoshapeevent_kinoshapemovement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KinoAnalysisState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
