# Generated by Django 5.2.14 on 2026-06-09 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kino", "0005_kinoanalysisstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="KinoBoardPatternEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[("row", "Row"), ("column", "Column")], max_length=20
                    ),
                ),
                ("group_number", models.IntegerField()),
                ("group_numbers", models.JSONField()),
                ("hit_numbers", models.JSONField()),
                ("hit_count", models.IntegerField()),
                ("threshold", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_pattern_events",
                        to="kino.kinodraw",
                    ),
                ),
            ],
            options={
                "ordering": ["draw__draw_time", "pattern_type", "group_number"],
                "indexes": [
                    models.Index(
                        fields=["pattern_type"], name="kino_kinobo_pattern_9068a9_idx"
                    ),
                    models.Index(
                        fields=["group_number"], name="kino_kinobo_group_n_9e3c98_idx"
                    ),
                    models.Index(
                        fields=["hit_count"], name="kino_kinobo_hit_cou_c26046_idx"
                    ),
                    models.Index(
                        fields=["threshold"], name="kino_kinobo_thresho_ce3462_idx"
                    ),
                    models.Index(
                        fields=["draw"], name="kino_kinobo_draw_id_4e5988_idx"
                    ),
                    models.Index(
                        fields=["pattern_type", "group_number"],
                        name="kino_kinobo_pattern_318828_idx",
                    ),
                ],
                "unique_together": {
                    ("draw", "pattern_type", "group_number", "threshold")
                },
            },
        ),
    ]
