# Generated by Django 5.2.14 on 2026-06-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kino", "0006_kinoboardpatternevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="KinoAIResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(default="number_ai_v1", max_length=100),
                ),
                ("train_draws", models.IntegerField(default=0)),
                ("test_draws", models.IntegerField(default=0)),
                ("baseline_top20_hits", models.FloatField(default=5.0)),
                ("model_top20_hits", models.FloatField(default=0)),
                ("lift", models.FloatField(default=0)),
                ("accuracy", models.FloatField(default=0)),
                ("precision", models.FloatField(default=0)),
                ("recall", models.FloatField(default=0)),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
